version: "3.8"
services:
  mysql-db:
    image: mysql/mysql-server:8.0
    container_name: dvd_mysql
    env_file:
      - docker-env.env
    volumes:
        - mydb_volume:/var/lib/mysql
    networks:
        - dvd_network

  restful-server:
    build: .
    image: dvd_spring_server
    container_name: dvd_spring_server
    networks:
      - dvd_network
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    env_file:
      - docker-env.env

networks:
  dvd_network:

volumes:
  mydb_volume:
