# Used by the enable-encryption.bat script to encrypt
# all secrets (at rest) in the cluster. This is still experimental
# and has not been extensively tested with minikube
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
    providers:
      - secretbox:
          keys:
            - name: key1
              secret: eANg1GfH/vZI8fiwZySMaNdiQE3pd0HFJ9uDI3z5PFU=
            - name: key2
              secret: kfezi6rgklI7GNIup9MYEf88VnLdS3MYustV8fkub04=
      - identity: {}
