FROM mysql:8.0.32

LABEL maintainer="Docker community and MySQL team"
LABEL author="Thomas Tomtsis, icsd15201@icsd.aegean.gr"
LABEL descritpion="Simple MySQL image for use with DVDApplication"

ENV MYSQL_ROOT_PASSWORD=icsd15201   \
    MYSQL_USER=icsd15201    \
    MYSQL_PASSWORD=password132  \
    MYSQL_DATABASE=mydb \
    MYSQL_TCP_PORT=3306