# InnoDB Cluster implementation through the use of MySQL Operator
# Operator was installed using Helm

apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: my-innodb-cluster
spec:
  secretName: db-secret
  imagePullPolicy: IfNotPresent
  tlsUseSelfSigned: true
  instances: 3
  edition: community

  router:
    instances: 1

  datadirVolumeClaimTemplate:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi