# InnoDB Cluster implementation through the use of MySQL Operator
# Operator was installed using Helm

apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: my-innodb-cluster
spec:
  secretName: db-secret
  imagePullPolicy: IfNotPresent
  tlsUseSelfSigned: true
  instances: 3
  edition: community

  router:
    instances: 1

  datadirVolumeClaimTemplate:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi

  backupProfiles:
  - name: daily-dvd-backup
    dumpInstance:
      dumpOptions:
        consistent: true

      storage:
        persistentVolumeClaim:
          # Backups are saved by default in /mnt/storage
          claimName: innodb-backup-pvc
  backupSchedules:
    - name: daily-midnight-backup
      schedule: "0 0 * * *"
      backupProfileName: daily-dvd-backup
      enabled: true