# Service for the Spring Boot REST Server
apiVersion: v1
kind: Service
metadata:
  name: rest-server-service
spec:
  selector:
    app: rest-server
    tier: server
  ports:
    - protocol: 'TCP'
      port: 8080
      targetPort: 8080
  type: LoadBalancer