version: "3.8"
services:
  mysql-db:
    build: /MySQLDocker
    image: dvd_mysql_server
    container_name: dvd_mysql
    volumes:
      - mydb_volume:/var/lib/mysql
    networks:
      - dvd_network
    environment:
      MYSQL_ROOT_PASSWORD: icsd15201
      MYSQL_USER: icsd15201
      MYSQL_PASSWORD: password132
      MYSQL_DATABASE: mydb

  restful-server:
    build: /SpringServer
    image: dvd_spring_server
    container_name: dvd_spring_server
    ports:
      - "8080:8080"
    networks:
      - dvd_network
    depends_on:
      - mysql-db
    environment:
      DATASOURCE_URL: jdbc:mysql://dvd_mysql:3306/mydb
      DB_USERNAME: icsd15201
      DB_PASSWORD: password132
      SPRING_PROFILES_ACTIVE: docker

networks:
  dvd_network:

volumes:
  mydb_volume:
