version: "3.8"
services:
  mysql-db:
    build: /MySQLDocker
    image: dvd_mysql_server
    container_name: ${MYSQL_CONTAINER_NAME}
    volumes:
      - mydb_volume:/var/lib/mysql
    networks:
      - dvd_network
    environment:
      MYSQL_ROOT_PASSWORD: $(MYSQL_ROOT_PASSWORD)
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_TCP_PORT: ${MYSQL_TCP_PORT}

  restful-server:
    build: /SpringServer
    image: dvd_spring_server
    container_name: dvd_spring_server
    ports:
      - "8080:8080"
    networks:
      - dvd_network
    depends_on:
      - mysql-db
    environment:
      DATASOURCE_URL: ${DATASOURCE_URL}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}

networks:
  dvd_network:

volumes:
  mydb_volume:
