# InnoDB Cluster implementation through the use of MySQL Operator
# Operator was installed using Helm

apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mycluster
spec:
  secretName: db-secret
  imagePullPolicy: IfNotPresent
  tlsUseSelfSigned: true
  instances: 3
  edition: community

  podSpec:
    containers:
      - name: dvd-mysql

        readinessProbe:
          exec:
            command:
              - mysqlsh
              - root:password132@mycluster:3306
              - --sql
              - --e
              - "CREATE USER 'icsd15201'@'%' IDENTIFIED BY 'password132';"
          initialDelaySeconds: 5
          periodSeconds: 2

  router:
    instances: 1

  datadirVolumeClaimTemplate:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi