apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-server-deployment
  labels:
    app: rest-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-server
      tier: server
  template:
    metadata:
      name: rest-server-pod
      labels:
        app: rest-server
        tier: server
    spec:
      containers:
        - name: dvd-spring-server
          image: ttomtsis/dvd-spring-server:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  key: spring_profiles_active
                  name: dvd-config

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: mysql_user
                  name: db-secret

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql_password
                  name: db-secret

            - name: DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: datasource_url
                  name: dvd-config
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 1