# Secret Containing the Database Credentials used
# Across ALL MySQL Server Pods, also contains the
# user that MySQL Router will initially use
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque

stringData:
  mysql_root_password: "icsd15201"

  # Used by the Spring Boot Server to connect to the database
  mysql_user: "root"
  mysql_password: "password132"

  rootUser: "root"
  rootHost: "%"
  rootPassword: "password132"