# StatefulSet for the MySQL Router:
# The cluster has been developed and tested
# by taking into account that only 1 router will be needed
# Router uses official MySQL Router Image from dockerhub
apiVersion:  apps/v1
kind: StatefulSet
metadata:
  name: mysql-router
spec:
  serviceName: "mysql-router-service"
  replicas: 1
  selector:
    matchLabels:
      app: mysql-server
      tier: router
  template:
    metadata:
      labels:
        app: mysql-server
        tier: router
    spec:
      setHostnameAsFQDN: true
      containers:
      - name: dvd-mysql-router
        image: mysql/mysql-router:8.0
        env:
          - name: MYSQL_HOST
            valueFrom:
              configMapKeyRef:
                key: mysql_router_host
                name: dvd-config

          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                key: mysql_router_user
                name: db-secret

          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: mysql_root_password
                name: db-secret

          - name: MYSQL_PORT
            valueFrom:
              configMapKeyRef:
                key: mysql_tcp_port
                name: dvd-config

          - name: MYSQL_CREATE_ROUTER_USER
            valueFrom:
              configMapKeyRef:
                key: mysql_router_create_user
                name: dvd-config