apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  clusterIP: None
  selector:
    app: mysql-server
    tier: database
  ports:
    - protocol: 'TCP'
      port: 3306
      targetPort: 3306
