FROM ibm-semeru-runtimes:open-17.0.6_10-jdk-focal
LABEL MAINTAINER="IBM SEMERU RUNTIMES"
LABEL AUTHOR="Thomas Tomtsis, icsd15201@icsd.aegean.gr"
RUN mkdir /opt/DVDApplication
COPY . /opt/DVDApplication

ENV DATASOURCE_URL=jdbc:mysql://dvd_mysql:3306/mydb
ENV DB_USERNAME=icsd15201
ENV DB_PASSWORD=password132
ENV SPRING_PROFILES_ACTIVE=docker

CMD ["java", "-jar", "/opt/DVDApplication/DVDApplication-0.0.1-SNAPSHOT.jar"]