apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server-deployment
  labels:
    app: mysql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-server
      tier: database
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysql-server
        tier: database
    spec:
      containers:
        - name: dvd-mysql
          image: mysql:8.0.32
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "icsd15201"

            - name: MYSQL_USER
              value: "icsd15201"

            - name: MYSQL_PASSWORD
              value: "password132"

            - name: MYSQL_DATABASE
              value: "mydb"

            - name: MYSQL_TCP_PORT
              value: "3306"